version: '3'

services:
  www:
    image: nginx:latest
    volumes:
      - ./www/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/app/dist:/usr/share/nginx/html
      - ./shared:/usr/share/nginx/html/assets/shared
    ports:
      - 80:80
    depends_on:
      - api

  api:
    image: maven:alpine
    volumes:
      - ./api:/app
      - maven-jar-repo:/root/.m2/
      - ./shared:/app/shared
    ports:
      - 8080:8080
    depends_on:
      - db
    working_dir: /app
    entrypoint: ./runnit.sh mvn spring-boot:run

  db:
    image: mariadb:10.2
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=blueforest
      - MYSQL_USER=nebuta
      - MYSQL_PASSWORD=s4mUr41w4rr10r

volumes:
  maven-jar-repo:
